### ISSUE TITLE
Allow user-specified block explorer

### ISSUE THREAD

**Issue by alex-miller-0** [GridPlus/abi-pack-framework#3]
Similar to how we added Polygonscan/Bscscan options in the `lattice-manager`, we should allow the user to specify that here. Currently all addresses are looked up using Etherscan, but we should add an attribute to metadata called `scannerUrl`, which can be e.g. `https://polygonscan.com`.

The `lattice-manager` should also have a dropdown to switch between networks to look for packs associated with that network. For example, the default should only load packs with either `etherscan.io` or `null` `scannerUrl`.

**Comment by douglance** [comment]
Do we want to specify the network on the contract pack level or on the address level? 

It could be like this: 

```
{
  "name": "AAVE",
  "version": "2",
  "desc": "Contract definitions from AAVE",
  "website": "https://docs.aave.com/developers/getting-started/deployed-contracts",
  "addresses": [
    {
      "address": "0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9",
      "network": "etherscan", // new value
      "tag": "LendingPool"
    },
    {
      "address": "0xDcD33426BA191383f1c9B431A342498fdac73488",
      "network": "polygon", // new value
      "tag": "WETH Gateway"
    }
  ]
 }
  ```

**Comment by alex-miller-0** [comment]
Good point. Let's do it at the address level. I will close the associated manager issue.

**Comment by alex-miller-0** [comment]
As discussed offline, let's do it at the address level as you suggest 👍
